from .language import dp
from .subject_handler import dp
from .answer_handler import dp
from .next_answer_handlers import dp
from .reset_handler import dp
from .check_test import dp
from .pagination import dp
from .delete_all import dp
from .pay_type import dp
from .reset_next_handler import dp
from .next2_answer_handler import dp
from .rest2_next_handler import dp