# Generated by Django 4.0.4 on 2022-04-20 23:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direction_name', models.CharField(max_length=60, verbose_name="Yo'nalish nomi")),
            ],
            options={
                'verbose_name': " OTM yo'nalishi ",
                'verbose_name_plural': " OTM yo'nalishlari ",
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=30, verbose_name='Til nomi')),
                ('language_code', models.CharField(max_length=5, verbose_name='Til codi')),
            ],
            options={
                'verbose_name': ' Bot tili ',
                'verbose_name_plural': ' Bot tillari ',
            },
        ),
        migrations.CreateModel(
            name='SelectedAnswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('subject_id', models.BigIntegerField()),
                ('right_answers', models.IntegerField()),
                ('wrong_answers', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('test_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=60, verbose_name='Fan nomi')),
            ],
            options={
                'verbose_name': ' Fan ',
                'verbose_name_plural': ' Fanlar ',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='User ID')),
                ('name', models.CharField(max_length=100, verbose_name='Foydalanuvchi ismi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Foydalanuvchi faol')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.language', verbose_name='Foydalanuvchi tili')),
            ],
            options={
                'verbose_name': ' Foydalanuvchi ',
                'verbose_name_plural': ' Foydalanuvchilar ',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Narxi')),
                ('directions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.direction', verbose_name="Yo'nalish")),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.language', verbose_name='Test tili')),
            ],
            options={
                'verbose_name': ' Test ',
                'verbose_name_plural': ' Testlar ',
            },
        ),
        migrations.CreateModel(
            name='DirectionSubjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=tests.models.filename_tests, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])], verbose_name='Test fayli')),
                ('keys', models.FileField(upload_to=tests.models.filename_keys, validators=[django.core.validators.FileExtensionValidator(['xlsx'])], verbose_name='Javoblar')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.subjects', verbose_name='Fan nomi')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.tests', verbose_name='Test')),
            ],
            options={
                'verbose_name': ' Fanlar majmuasi ',
                'verbose_name_plural': ' Fanlar majmuasi ',
            },
        ),
    ]
